site_name: NicholasChebski
site_url: https://nicholaschebski.github.io/

docs_dir: src
site_dir: site

theme:
  name: null
  custom_dir: vibe_theme/

watch:
  - vibe_theme

nav:
  - Main: index.md
  - Study projects: study.md
  - Other staff: unstudy.md
  - Lab 1: README-1.md
  - Lab 2: README-2.md
  - Lab 4: README-4.md
  - Lab 5: README-5.md
